language: haskell
ghc:
  #- 7.8
  - 7.6
  #- 7.4

before_install:
  - cabal update
  - cabal install happy alex
  - export PATH=$HOME/.cabal/bin:$PATH

install:
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests

before_script:
    - cabal configure --enable-tests
    - cabal build

script:
    - cabal test --show-details=always --test-options="--color"